from http import HTTPStatus

ALLOWED_HOSTS_DEFAULT = "localhost,127.0.0.1,[::1]"
DEFAULT_SECRET_KEY = "django-insecure-local-dev-key"
TEMPLATES_DIR = "templates_var3"

POSTGRES_DB_DEFAULT = "team_finder"
POSTGRES_USER_DEFAULT = "team_finder"
POSTGRES_PASSWORD_DEFAULT = "team_finder"
POSTGRES_HOST_DEFAULT = "localhost"
POSTGRES_PORT_DEFAULT = 5436

LANGUAGE_CODE = "ru-ru"
TIME_ZONE = "Europe/Moscow"

PROJECT_NAME_MAX_LENGTH = 200
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
SKILL_NAME_MAX_LENGTH = 124

PROJECTS_PER_PAGE = 12
PARTICIPANTS_PER_PAGE = 12
SUGGESTIONS_LIMIT = 10

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
)
PROJECT_STATUS_MAX_LENGTH = max(len(status) for status, _ in PROJECT_STATUS_CHOICES)

AVATAR_SIZE = (200, 200)
AVATAR_FONT_SIZE = 100
AVATAR_TEXT_COLOR = (255, 255, 255)
AVATAR_PALETTE = (
    (52, 152, 219),
    (46, 204, 113),
    (155, 89, 182),
    (241, 196, 15),
    (26, 188, 156),
    (230, 126, 34),
)

HTTP_BAD_REQUEST = HTTPStatus.BAD_REQUEST
